<br><br><br><a href="/">
<img src="http://cs.usfca.edu/~bjherger/yotta/logo.jpg" alt="Yotta. 10^24 of knolwedge" width="480" height="216"></a>
<br><br><br><br>
<form method="post" action="/">
<table cellspacing="0" cellpadding="2">
<h1>
<input type="text" name="query" maxlength="50" size="60" font-size:40px; style="width:600px; height:40px;"> 
<input type="submit"; value="Yotta Search!"; autocomplete="off"; style="border-style:none";>
</form>
<br><br>

<div id = "content">
<h1>(<a href="/login">Login</a>)
(<a href="/register">Register</a>)</h1>
</div>

